// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQvcSsKBmNxJSxBeN040adMj8_BcPV5tM',
    appId: '1:695131986619:web:d792a29e6d36093998e79e',
    messagingSenderId: '695131986619',
    projectId: 'product-list-app-a0f5a',
    authDomain: 'product-list-app-a0f5a.firebaseapp.com',
    storageBucket: 'product-list-app-a0f5a.firebasestorage.app',
    measurementId: 'G-93E72Z7VM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR2329_kkcLxU8YTY_0_rzNZDvbAYu5T4',
    appId: '1:695131986619:android:f2cba48cd8fa927598e79e',
    messagingSenderId: '695131986619',
    projectId: 'product-list-app-a0f5a',
    storageBucket: 'product-list-app-a0f5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXkh5n9q4B0udFzO6IIUn-Cq06E-gnbz0',
    appId: '1:695131986619:ios:4f4606e7cfc0d1bd98e79e',
    messagingSenderId: '695131986619',
    projectId: 'product-list-app-a0f5a',
    storageBucket: 'product-list-app-a0f5a.firebasestorage.app',
    iosBundleId: 'com.example.productListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXkh5n9q4B0udFzO6IIUn-Cq06E-gnbz0',
    appId: '1:695131986619:ios:4f4606e7cfc0d1bd98e79e',
    messagingSenderId: '695131986619',
    projectId: 'product-list-app-a0f5a',
    storageBucket: 'product-list-app-a0f5a.firebasestorage.app',
    iosBundleId: 'com.example.productListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQvcSsKBmNxJSxBeN040adMj8_BcPV5tM',
    appId: '1:695131986619:web:0395d04b1597be9d98e79e',
    messagingSenderId: '695131986619',
    projectId: 'product-list-app-a0f5a',
    authDomain: 'product-list-app-a0f5a.firebaseapp.com',
    storageBucket: 'product-list-app-a0f5a.firebasestorage.app',
    measurementId: 'G-55N1YWXBFQ',
  );
}
